modeling:
  test_size: 0.2
  val_size: 0.2
  random_seed: 42
  random_forest:
    n_estimators: 100
    max_depth: 15
    min_samples_split: 4
    min_samples_leaf: 3
    n_jobs: -1
    max_features: 0.5
    oob_score: true

data:
  clean_data: 'data/cleanCensusData.csv'
  raw_data: 'starter_code/data/rawCensusData.csv'